# Generated by Django 4.1.7 on 2023-03-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scrape', models.DateField(auto_now=True, verbose_name='Date Scrapped')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.CharField(max_length=255, verbose_name='Price')),
            ],
        ),
    ]
