# Generated by Django 4.1.7 on 2023-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name2',
            field=models.CharField(default=1, max_length=255, verbose_name='Name2'),
            preserve_default=False,
        ),
    ]
