# Generated by Django 4.1.7 on 2023-03-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_food_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name2',
        ),
    ]
