# Generated by Django 4.1.7 on 2023-03-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_food_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_scrape',
            field=models.CharField(max_length=255, verbose_name='Date Scrapped'),
        ),
    ]
