# Generated by Django 4.1.7 on 2023-03-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_webuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='date_scrape',
            new_name='date',
        ),
    ]
