# Generated by Django 4.1.7 on 2023-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_webuser_alter_food_date_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='Brand'),
        ),
    ]
